
//----------------------
// <auto-generated>
//     Generated by LazyStack. Do not modify, your changes will be overwritten.
//     If you need to register additional services, do it in a separate class.
//     Also, if you need to register a service with a different lifetime, do it in a seprate class.
//     Note that we are using Try* so if you register a service with the same interface first, that 
//     registration will be used.   
//     We very intentionally use Singletons for our Repos. This is because we want to be able to 
//     maintain state for caching etc. when necessary. 
// </auto-generated>
//----------------------
using LazyStack.Notifications.Repo; // Can't be project global because of namespace
namespace Microsoft.Extensions.DependencyInjection.Extensions;
public static class LzNotificationsRepoExtensions
{
    public static IServiceCollection AddLzNotificationsRepoSvc(this IServiceCollection services)
    {
		services.TryAddSingleton<ILzNotificationRepo, LzNotificationRepo>();
		services.TryAddSingleton<ILzSubscriptionRepo, LzSubscriptionRepo>();

        return services;
    }
}
